# this is for demo, yaml can be used instead of .properties but don't mix the two in real life
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

# custom props
app:
  version: 1.0.0

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #      include: info, health, metrics, loggers, beans, mappings, readiness
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

# Data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: postgres

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true


