# this is for demo, yaml can be used instead of .properties but don't mix the two in real life
server:
  port: 8080
# custom props
app:
  version: 1.0.0
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #      include: info, health, metrics, loggers, beans, mappings, readiness
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true